# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    loader.grub.enable = false;
    loader.systemd-boot.enable = true;
    loader.systemd-boot.configurationLimit = 5;
    loader.efi.efiSysMountPoint = "/boot";
    loader.efi.canTouchEfiVariables = true;
    initrd = {
      availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
      kernelModules = [ ];
      luks.devices.root = {
        crypttabExtraOpts = [ "fido2-device=auto" ];
        device = "/dev/disk/by-uuid/83002f79-e9a4-429b-8695-fc9b90f640e8";
      };
      systemd = {
        enable = true;
        extraBin = {
          setleds = "${pkgs.kbd}/bin/setleds";
        };
        services.numlock = {
          enable = true;
          before = [ "cryptsetup.target" ];
          wantedBy = [ "initrd.target" ];
          serviceConfig = {
            Type = "oneshot";
          };
          script = ''
            /bin/setleds -D +num < /dev/tty1
          '';
        };
      };
    };
    kernelPackages = pkgs.linuxPackages_6_19;
    kernelModules = [ "kvm-amd" "ntsync" ];
    extraModulePackages = [ ];
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/27630f6a-1ed9-4965-8afe-1e95de28ff7a";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D4B0-72B6";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  networking = {
    hostName = "glitternix"; # Define your hostname.
    wireless = {
      enable = true;
      networks."beamish".psk = "ostepop1990!#";
      #networks."Beamish+".psk = "ostepop1990!#";
    };
    useDHCP = true;
    dhcpcd.extraConfig = ''
      nohook resolv.conf
    '';
  };

  nixpkgs.config.rocmSupport = true;

  hardware.graphics = {
    enable = true;
  };

  hardware.bluetooth.enable = true;

  services.xserver.videoDrivers = ["amdgpu"];
}
