export DOTDIR=$HOME/dot

export XDG_RUNTIME_DIR=$HOME/.xdg-runtime-dir

ppath=($DOTDIR/dotfiles/bin $HOME/bin)

if [ "$(uname)" = "Darwin" ]; then
  ppath+=$HOME/dot/dotfiles/bin/macos
  ppath+=/opt/homebrew/bin
  ppath+=/opt/homebrew/sbin
fi

if $(uname -a | grep -qi microsoft); then
  ppath+=$HOME/dot/dotfiles/bin/wsl
fi

# Source custom settings
if [[ -s "$HOME/.zshenv_custom" ]]; then
  source "$HOME/.zshenv_custom"
fi
path=($ppath[@] $path[@])
export PATH
