# znap
source "$HOME/dot/zsh-snap/znap.zsh"

setopt BANG_HIST                 # Treat the '!' character specially during expansion.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire a duplicate event first when trimming history.
setopt HIST_IGNORE_DUPS          # Do not record an event that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete an old recorded event if a new event is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a previously found event.
setopt HIST_IGNORE_SPACE         # Do not record an event starting with a space.
setopt HIST_SAVE_NO_DUPS         # Do not write a duplicate event to the history file.
setopt HIST_VERIFY               # Do not execute immediately upon history expansion.
setopt HIST_BEEP                 # Beep when accessing non-existent history.

HISTFILE=$DOTDIR/zsh-history
HISTSIZE=10000
SAVEHIST=10000

znap source zsh-users/zsh-syntax-highlighting
znap source zsh-users/zsh-history-substring-search
znap source zsh-users/zsh-autosuggestions
function pmodload() { true }
zstyle ':prezto:module:editor' key-bindings 'vi'
znap source sorin-ionescu/prezto modules/git modules/ssh modules/editor
bindkey -M viins "$key_info[Up]" history-substring-search-up
bindkey -M viins "$key_info[Down]" history-substring-search-down

# Makes the right enter key work in zsh
bindkey -s "^[OM" "^M"

# Variables
export VISUAL=vim
export EDITOR=vim
export LESS='-F -g -R -X -z-4'

## Completion
if which kubectl >/dev/null; then
  source <(kubectl completion zsh)
  compdef _kubectl kc
fi

# Aliases
alias cr="code -r"
alias cr.="code -r ."
alias ll="ls -l"
alias la="ls -la"

# WSL specific stuff
if grep -qEi "(Microsoft|WSL)" /proc/version &> /dev/null ; then
  source "$HOME/dot/dotfiles/zsh/zshrc_wsl"
fi

# Source custom settings
if [ -s "$HOME/.zshrc_custom" ]; then
  source "$HOME/.zshrc_custom"
fi

if [ -z $TMUX ]; then
  echo "Remember to tmux"
fi
znap prompt tg90nor/prompt
true
